Changes in github CI

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -19,8 +19,16 @@ jobs:
     #- uses: actions/checkout@v2
     - name: Deploy to production
       run: |
+        # Get password for posrgres user
+        PG_PASSWORD=$(/root/linuxscripts/get_postgres_password.sh $ENVIRONMENT_NAME)
+        
+        if [ $? -ne 0 ];
+        then
+          echo "System has failed to get postgres password"
+          exit 1
+        fi
         # Set environment variables requires for manage.py commands
-        export DJANGO_SETTINGS_MODULE=helpmecorona.settings.$ENVIRONMENT_NAME
+        export DJANGO_SETTINGS_MODULE=helpmecorona.settings.prod
         export DJANGO_STATIC_ROOT=helpmecorona/static
         export GOOGLE_APPLICATION_CREDENTIALS_CONTENT="{  \"type\": \"service_account\",  \"project_id\": \"conta-comigo-app-files\",  \"private_key_id\": \"2c2d90afee1426ab87de591b6863ebc9c7820372\",  \"private_key\": \"-----BEGIN PRIVATE KEY-----\nMIIEvQIBADA$"
         export DATABASE_URL=postgres://contacomigoprod:$PG_PASSWORD@localhost:5432/contacomigo_prod
